version: "3.9"

services: 
    laravel:
        build: 
            context: .
            dockerfile: ./devcontainer/laravel.dockerfile
        ports: 
            - 8000:80
        volumes: 
            - ./:/app
        environment: 
            - DB_HOST=mysql
            - DB_CONNECTION=mysql
            - DB_DATABASE=mexicana
            - DB_USERNAME=root
            - DB_PASSWORD=mexicana123
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            - MYSQL_DATABASE=mexicana
            - MYSQL_ROOT_PASSWORD=mexicana123
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes